language: go

go:
  - "1.15.x"

env:
  - GO111MODULE=on

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/go-build  # Build cache
    - $HOME/gopath/pkg/mod   # Go modules

script: make test
